[package]
name = "raw-flowcheck"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ark-bn254 = "0.4.0"
ark-ff = "0.4.2"
light-poseidon = "0.2.0"
num-bigint = "0.4.4"
rustc-serialize = "0.3.25"

