[package]
name = "risc0-cw-verifier"
version = "0.1.0"
edition = "2021"

[dependencies]
risc0-zkp = { version = "0.21.0", default-features = false }
risc0-zkvm = { version = "0.21.0", default-features = false }

